name: Remove Label
description: Removes a label from an issue.

inputs:
  issue-number:
    description: The issue number.
    required: true
  label:
    description: The label name to remove.
    required: true

runs:
  using: composite
  steps:
    - name: Remove label
      uses: actions/github-script@v8
      with:
        script: |
          await github.rest.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }},
            name: '${{ inputs.label }}'
          });
