name: Add Assignee
description: Adds an assignee to an issue.

inputs:
  issue-number:
    description: The issue number.
    required: true
  assignee:
    description: The GitHub username to add.
    required: true

runs:
  using: composite
  steps:
    - name: Add assignee
      uses: actions/github-script@v9
      with:
        script: |
          await github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }},
            assignees: ['${{ inputs.assignee }}']
          });
