name: Add Label
description: Adds a label to an issue.

inputs:
  issue-number:
    description: The issue number.
    required: true
  label:
    description: The label name to add.
    required: true

runs:
  using: composite
  steps:
    - name: Add label
      uses: actions/github-script@v8
      with:
        script: |
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.issue-number }},
            labels: ['${{ inputs.label }}']
          });
